EPUI-14-ban-users + tests + register misc
IgorSteps/easypark-ui pull request #16
Opened 2024-05-10 23:39 UTC by Lewissp312

# Pull Request

## Ticket link
https://trello.com/c/mbnG4EOW

## Why have you made these changes? What problem it fixes?
N/A

## What does this implement? Explain your changes
Allows the admin to ban users. Also some slight register changes and additions

## Is it better than when you found it?
N/A

## Comments
Cypress test currently does not work as it is experiencing CORS issues with patch command. This does not happen in normal use or with the normal js test

2024-05-11 17:07 UTC, IgorSteps requested changes
Good start, but we should create a separate page with all drivers(there is a `DriversList` [component](https://github.com/IgorSteps/easypark-ui/blob/main/src/views/components/driversList.js) that exists). We can add `Ban` button to the `Driver Card` [component](https://github.com/IgorSteps/easypark-ui/blob/main/src/views/components/driverCard.js) which on click sends the request to ban the driver.

We should really do the same for the parking lots. The admin dashboard should list all parking lots and each parking lot should have a `Delete` button. But that should be another ticket and done as a separate PR...

2024-05-11 17:07 UTC, IgorSteps commented on src/views/components/admin/banUserForm.js
> +                    Delete
Should be Ban instead of Delete, since we are banning users and not deleting them

2024-05-13 21:16 UTC, IgorSteps requested changes
Very good work, some nits

2024-05-13 21:16 UTC, IgorSteps commented on src/views/components/admin/banUserForm.js
> -                    Delete
Is this needed now, given that we have the 'Ban' button in the drivers list component

2024-05-13 21:16 UTC, IgorSteps commented on src/views/components/driverCard.js
> +    const { banUserResult, handleBanUser, banUserError } = useBanUser();
We should have [Alerts](https://react-bootstrap.netlify.app/docs/components/alerts/) to specify this ban operation succeeded or errored

2024-05-13 21:16 UTC, IgorSteps commented on src/views/components/driverCard.js
>              <Card data-test-id="driver-card">
You can add `className="mb-3"` to add some padding at the bottom to separate cards a bit

2024-05-13 21:16 UTC, IgorSteps commented on cypress/e2e/banUser.cy.js
> -        cy.populateWithDrivers()
If you don't populate DB with Users how can you ban anyone? Does this test pass?

2024-05-15 19:15 UTC, Lewissp312 commented on cypress/e2e/banUser.cy.js
> -        cy.populateWithDrivers()
The test creates a user using the register page. I removed that line so that the created user would be the only one there, allowing me to use "driver-0" to find the elements

2024-05-15 19:39 UTC, IgorSteps reviewed
Nice, I think messaging should work already - the chat modal is functional and you are passing userID into it?

2024-05-15 19:39 UTC, IgorSteps commented on src/views/components/driverCard.js
> +                            {banUserError}
Let's prepend "Failed to ban user: " to it

2024-05-15 20:17 UTC, IgorSteps commented on cypress/e2e/banUser.cy.js
> +describe('Ban User Form', () => {
Can you also write a test to message a user, I made on from the driver side https://github.com/IgorSteps/easypark-ui/blob/main/cypress/e2e/messageAdmin.cy.js

2024-05-15 23:52 UTC, IgorSteps approved these changes
Great work

2024-05-16 09:26 UTC, merged